project: boasdasdotstrap

storage:
  default: asdasd
  backup: asdasd
  ssd: asdasd

versions:
  verdaccio: 6.1.6
  gitea: 12.4.0
  giteaactions: 0.0.2

domains:
  internal: asd
  external: asd

redis:
  version: 8

  resources:
    cpu: 50m
    memory: 256Mi