project: boasdasdotstrap

storage:
  default: asdasd
  backup: asdasd
  ssd: asdasd

versions:
  redis: 8
  verdaccio: 6.1.6
  gitea: 12.4.0
  giteaactions: 0.0.2

domains:
  internal: asd
  external: asd
