project: boasdasdotstrap

storage:
  default: asdasd
  nobackup: asdasd
  fast: asdasd

versions:
  gitea: 12.4.0
  giteaactions: 0.0.2

domains:
  internal: asd
  external: asd

redis:
  image:
    registry: ""
    repository: redis
    tag: 8

  resources:
    cpu: 50m
    memory: 256Mi

pypi:
  image:
    registry: ""
    repository: pypiserver/pypiserver
    tag: latest

  resources:
    cpu: 100m
    memory: 64Mi

npm:
  image:
    registry: ""
    repository: verdaccio/verdaccio
    tag: 6.1.6

  resources:
    cpu: 750m
    memory: 400Mi

registry:
  image:
    registry: ""
    repository: registry
    tag: latest

  resources:
    memory: 128Mi

bandersnatch:
  image:
    registry: ""
    repository: pypa/bandersnatch
    tag: 3.14

  resources:
    cpu: 100m
    memory: 64Mi

  packages:
    - absl-py
    - adbc-driver-postgresql
    - adbc-driver-sqlite
    - adlfs
    - aiohttp
    - aiomysql
    - aioodbc
    - aiosqlite
    - alembic
    - altair
    - annotated-types
    - anyio
    - arro3-core
    - arviz
    - asgiref
    - astunparse
    - async-timeout
    - asyncmy
    - asyncpg
    - beautifulsoup4
    - blinker
    - bodo
    - boto3
    - botocore
    - bottleneck
    - build
    - cachetools
    - certifi
    - chardet
    - charset_normalizer
    - click
    - colorama
    - coverage
    - cryptography
    - cx_oracle
    - daft
    - dataframe-api-compat
    - datafusion
    - delta-spark
    - deltalake
    - deprecated
    - distro
    - dnspython
    - duckdb
    - email-validator
    - et-xmlfile
    - fastparquet
    - fido2
    - flask
    - flatbuffers
    - fsspec
    - gast
    - gcsfs
    - gevent
    - google-api-python-client
    - google-auth
    - google-cloud-bigquery
    - google-meridian
    - google_pasta
    - googleapis-common-protos
    - greenlet
    - grpcio
    - grpcio-status
    - gssapi
    - h5py
    - hiredis
    - html5lib
    - httpx
    - httpx-aiohttp
    - huggingface-hub
    - hypothesis
    - id
    - idna
    - immutabledict
    - importlib-metadata
    - itsdangerous
    - jax
    - jaxlib
    - jinja2
    - jiter
    - jmespath
    - joblib
    - jsonpatch
    - keras
    - kerberos
    - keyring
    - kubernetes
    - langchain
    - langchain-anthropic
    - langchain-aws
    - langchain-azure-ai
    - langchain-community
    - langchain-core
    - langchain-deepseek
    - langchain-fireworks
    - langchain-google-genai
    - langchain-google-vertexai
    - langchain-groq
    - langchain-huggingface
    - langchain-mistralai
    - langchain-ollama
    - langchain-openai
    - langchain-perplexity
    - langchain-together
    - langchain-xai
    - langgraph
    - langgraph-checkpoint
    - langgraph-prebuilt
    - langgraph-sdk
    - langsmith
    - libclang
    - librt
    - lxml
    - mako
    - mariadb
    - markupsafe
    - matplotlib
    - ml_dtypes
    - mlflow
    - mmh3
    - mmm-proto-schema
    - mypy
    - mypy_extensions
    - mysql-connector-python
    - mysqlclient
    - natsort
    - numba
    - numexpr
    - numpy
    - nvidia-cublas-cu12
    - nvidia-cuda-cupti-cu12
    - nvidia-cuda-nvcc-cu12
    - nvidia-cuda-nvrtc-cu12
    - nvidia-cuda-runtime-cu12
    - nvidia-cudnn-cu12
    - nvidia-cufft-cu12
    - nvidia-curand-cu12
    - nvidia-cusolver-cu12
    - nvidia-cusparse-cu12
    - nvidia-nccl-cu12
    - nvidia-nvjitlink-cu12
    - odfpy
    - openai
    - openpyxl
    - opentelemetry-api
    - opentelemetry-exporter-otlp-proto-http
    - opentelemetry-sdk
    - opt_einsum
    - oracledb
    - orjson
    - packaging
    - pandas
    - pandas-gbq
    - pandas-stubs
    - pathspec
    - pg8000
    - pika
    - pip
    - polars
    - protobuf
    - psutil
    - psycopg
    - psycopg2
    - psycopg2-binary
    - psycopg2cffi
    - py4j
    - pyarrow
    - pyarrow-stubs
    - pybreaker
    - pydantic
    - pydantic-core
    - pyiceberg
    - pyiceberg-core
    - pyink
    - pyjwt
    - pylint
    - pymssql
    - pymysql
    - pyodbc
    - pyopenssl
    - pyparsing
    - pyproject_hooks
    - pyqt5
    - pyreadstat
    - pyroaring
    - pysocks
    - pyspark
    - pytest
    - pytest-xdist
    - python-calamine
    - python-dateutil
    - python-dotenv
    - python-snappy
    - pytz
    - pyxlsb
    - pyyaml
    - qtpy
    - ray
    - readme-renderer
    - redis
    - requests
    - requests-toolbelt
    - rfc3986
    - rich
    - s3fs
    - s3transfer
    - scipy
    - semver
    - servc
    - setuptools
    - simplejson
    - six
    - sniffio
    - sortedcontainers
    - sounddevice
    - sqlalchemy
    - sqlcipher3_binary
    - sqlgot
    - statsmodels
    - strictyaml
    - tables
    - tabulate
    - tenacity
    - tensorboard
    - tensorflow
    - tensorflow-io-gcs-filesystem
    - tensorflow-probability
    - termcolor
    - tf-keras
    - thrift
    - thrift-sasl
    - tiktoken
    - tomli
    - tornado
    - tqdm
    - twine
    - twisted
    - types-pyopenssl
    - types-pytz
    - types-pyyaml
    - types-redis
    - types-requests
    - types-simplejson
    - typing-extensions
    - typing-inspection
    - typing_extensions
    - tzdata
    - urllib3
    - uuid-utils
    - uv
    - virtualenv
    - websockets
    - werkzeug
    - wrapt
    - xarray
    - xlrd
    - xlsxwriter
    - xxhash
    - zstandard

postgres:
  resources:
    memory: 512Mi
