apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bandersnatch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.storage.nobackup }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bandersnatch-config
data:
  bandersnatch.conf: |
    [mirror]
    directory = /data/packages
    master = https://pypi.org
    json = true
    workers = 2
    stop-on-error = true

    [plugins]
    enabled =
        allowlist_project
        allowlist_release

    [allowlist]
    packages =
{{ if .Values.bandersnatch.packages }}
{{- range sortAlpha .Values.bandersnatch.packages }}
        {{ . }}
{{- end }}
{{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandersnatch
  labels:
    app: bandersnatch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bandersnatch
  template:
    metadata:
      labels:
        app: bandersnatch
    spec:
      volumes:
        - name: pypidata
          persistentVolumeClaim:
            claimName: bandersnatch
        - name: bandersnatch-config
          configMap:
            name: bandersnatch-config
      containers:
        - name: bandersnatch
          image: {{ .Values.bandersnatch.image.registry }}{{ .Values.bandersnatch.image.repository }}:{{ .Values.bandersnatch.image.tag }}
          resources:
            {{- with.Values.bandersnatch.resources }}
            requests:
              {{- toYaml . | nindent 14 }}
            limits:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          command:
            - /bin/bash
          args:
            - -c
            - python3 -m http.server 8080 --bind 0.0.0.0 --directory /data/packages/web
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
          volumeMounts:
            - name: pypidata
              mountPath: /data/packages
            - name: bandersnatch-config
              mountPath: /etc/bandersnatch
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: bandersnatch-sync
  labels:
    app: bandersnatch
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: bandersnatch
            role: sync
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: pypidata
              persistentVolumeClaim:
                claimName: bandersnatch
            - name: bandersnatch-config
              configMap:
                name: bandersnatch-config
          containers:
            - name: mirror-packages
              image: {{ .Values.bandersnatch.image.registry }}{{ .Values.bandersnatch.image.repository }}:{{ .Values.bandersnatch.image.tag }}
              command:
                - bandersnatch
              args:
                - --config
                - /etc/bandersnatch/bandersnatch.conf
                - mirror
              volumeMounts:
                - name: pypidata
                  mountPath: /data/packages
                - name: bandersnatch-config
                  mountPath: /etc/bandersnatch
---
apiVersion: v1
kind: Service
metadata:
  name: bandersnatch
  labels:
    app: bandersnatch
spec:
  selector:
    app: bandersnatch
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bandersnatch
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/target: mordorhome.{{ .Values.domains.external }}
    # external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - "*.{{ .Values.domains.external }}"
      secretName: wildcard-external
  ingressClassName: nginx
  rules:
    - host: bandersnatch.{{ .Values.domains.external }}
      http:
        paths:
          - backend:
              service:
                name: bandersnatch
                port:
                  number: 8080
            path: /
            pathType: Prefix
