apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials-main
spec:
  secretStoreRef:
    name: external-infra
    kind: ClusterSecretStore
  target:
    name: postgres-credentials-main
  data:
    - secretKey: password
      remoteRef:
        key: DB_POSTGRES
        property:  PASSWORD
    - secretKey: giteapassword
      remoteRef:
        key: DB_POSTGRES
        property:  PASSWORD-defaultgitea
    - secretKey: bitwardenpassword
      remoteRef:
        key: DB_POSTGRES
        property:  PASSWORD-mordorbitwarden
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-postgres
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  destination:
    namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc
  project: {{ .Values.project }}
  source:
    path: "charts/postgres"
    repoURL: "https://github.com/drgroot/kubespray.git"
    targetRevision: HEAD
    helm:
      releaseName: main
      values: |-
        fullnameOverride: main

        annotations:
          tailscale.com/expose: "true"

        storageclass: {{ .Values.storage.fast }}

        backup:
          storageclass: {{ .Values.storage.default }}

        resources:
          {{- with.Values.postgres.resources }}
          requests:
            {{- toYaml . | nindent 12 }}
          limits:
            {{- toYaml . | nindent 12 }}
          {{- end }}

        server:
          password:
            secretname: postgres-credentials-main
          additionalUsers:
            - name: bitwarden
              passwordkey: bitwardenpassword
              schema: bitwarden
            - name: gitea
              passwordkey: giteapassword
              schema: gitea
            - name: coder
              passwordkey: password
              schema: coder

        pushsecret:
          secretstore: kubernetes
          secretStoreKind: ClusterSecretStore
          remoteKey: main-postgres-credentials