---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-htpasswd
spec:
  secretStoreRef:
    name: external-infra
    kind: ClusterSecretStore
  target:
    name: registry-htpasswd
    template:
      type: Opaque
      data:
        htpasswd: "{{ `{{ htpasswd .PRIVATE_USERNAME .PRIVATE_PASSWORD }}` }}"
  data:
    - remoteRef:
        key: DOCKER_PRIVATE
        property: username
      secretKey: PRIVATE_USERNAME
    - remoteRef:
        key: DOCKER_PRIVATE
        property: password
      secretKey: PRIVATE_PASSWORD
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: {{ .Values.storage.nobackup }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - env:
          - name: REGISTRY_AUTH
            value: htpasswd
          - name: REGISTRY_AUTH_HTPASSWD_REALM
            value: Registry Realm
          - name: REGISTRY_AUTH_HTPASSWD_PATH
            value: /auth/htpasswd
          - name: REGISTRY_STORAGE_MAINTENANCE
            value: |
              uploadpurging:
                enabled: true
                age: 48h
                interval: 24h
                dryrun: false
              readonly:
                enabled: false
              delete:
                enabled: true
          image: {{ .Values.registry.image.registry }}/{{ .Values.registry.image.repository }}:{{ .Values.registry.image.tag }}
          name: app
          resources:
            {{- with.Values.registry.resources }}
            requests:
              {{- toYaml . | nindent 14 }}
            limits:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          ports:
            - containerPort: 5000
              name: port-5000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/registry
              name: config
            - mountPath: /auth
              name: htpasswd
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: registry
        - name: htpasswd
          secret:
            defaultMode: 420
            secretName: registry-htpasswd
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  ports:
    - name: port-5000
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: registry
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/target: mordorhome.{{ .Values.domains.external }}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/client-body-buffer-size: 5000m
    nginx.ingress.kubernetes.io/proxy-body-size: 5000m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: registry
spec:
  ingressClassName: nginx
  rules:
    - host: registry.{{ .Values.domains.external }}
      http:
        paths:
          - backend:
              service:
                name: registry
                port:
                  number: 5000
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - '*.{{ .Values.domains.external }}'
      secretName: wildcard-external
