image: postgres:16.3
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

annotations: {}

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "250m"
    memory: "512Mi"

storageclass: nfs-thorin-ssd-raid0

server:
  password:
    secretname: postgres-password
    key: password
  databasename: postgres
  username: postgres

  additionalUsers: []
    # - name: test
    #   passwordkey: password-test
    #   schema: test

pushsecret:
  enabled: true
  secretstore: default
  secretStoreKind: SecretStore
  remoteKey: postgres-credentials

backup:
  schedule: "0 0 * * *"
  storageclass: nfs-thorin-backups
